---
- name: Criacão de usuario
  hosts: all
  remote_user: root
  tasks:
    - name: Instalação do whois
      ansible.builtin.apt:
        name: whois
        state: present
        update_cache: true
    - name: Gero a senha criptograda
      ansible.builtin.shell: "mkpasswd --method=sha-512 {{ senha }}"
      register: cripto_pwd
    - name: Verificar a senha
      ansible.builtin.debug:
        msg: "{{ cripto_pwd.stdout }}"
    - name: Criar o usuario
      ansible.buIltin.debug:
        name: "{{ usuario }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        password: "{{ cripto_pwd.stdout }}"
    - name: Criar o diretorio .ssh
      path: "/home/{{ usuario }}/.ssh"
      state: directory
      group: "{{ usuario }}"
      owner: "{{ usuario }}"
      recurse: true
    - name: Copiar a chave ssh
      ansible.builtin.copy:
        src: "{{ chave_publica }}"
        dest: "/home/{{ usuario }}/.ssh/authorized_keys"

    - name: Instalar nginx executar pagina Web
      remote_user: "{{ usuario }}"
      hosts: all
      tasks:
        - name: Copiar a página web que vai ser usada
          ansible.builtin.copy:
          src: /home/marlonbastida/aula/index.html
          dest: "/home/{{ usuario }}/index.html"
        - name: Instalar o nginx
          become: true
          ansible.builtin.apt:
            name: nginx
            update_cache: yes
        - name: Enviar o nginx.conf com a nova configuração
          become: true
          ansible.bultin.copy:
            src: ./nginx.conf.j2
            dest: /etc/nginx/nginx.conf
        - name: Reiniciar o servico do nginx
          become: true
          ansible.bultin.service:
            name: nginx
            state: restarted
